image: node:13.1

stages:
    - setup
    - build
    # - test
    - deploy

node:install:
    stage: setup
    script:
        - npm i
    cache:
        key: $CI_COMMIT_REF_SLUG
        paths:
            - node_modules/
        policy: pull-push
    artifacts:
        paths:
            - node_modules/

build:
    stage: build
    script:
        - npm run build
    cache:
        key: $CI_COMMIT_REF_SLUG
        paths:
            - node_modules/
        policy: pull-push
    artifacts:
        paths:
            - build/

# test:
#     image: docker:19.03.1
#     stage: test
#     script:
#         - docker ps -a
#     cache:
#         key: $CI_COMMIT_REF_SLUG
#         paths:
#             - node_modules/
#         policy: pull-push

# docker:dev:deploy:
#     except:
#         - master
#     image:
#         name: docker/compose:1.24.1
#         entrypoint: ["/bin/sh", "-c"]
#     stage: deploy
#     script:
#         - docker-compose -f dnb_docker/docker-compose.dev.yml build
#         - docker-compose -f dnb_docker/docker-compose.dev.yml up -d
#     cache:
#         key: $CI_COMMIT_REF_SLUG
#         paths:
#             - node_modules/
#         policy: pull-push

# docker:dev:stop:
#     when: manual
#     image:
#         name: docker/compose:1.24.1
#         entrypoint: ["/bin/sh", "-c"]
#     stage: deploy
#     script:
#         - docker-compose -f dnb_docker/docker-compose.dev.yml down
#     cache:
#         key: $CI_COMMIT_REF_SLUG
#         paths:
#             - node_modules/
#         policy: pull-push

docker:production:deploy:
    only:
        - master
    image:
        name: docker/compose:1.24.1
        entrypoint: ["/bin/sh", "-c"]
    stage: deploy
    script:
        - docker-compose -f dnb_docker/docker-compose.yml build
        - docker-compose -f dnb_docker/docker-compose.yml up -d
    cache:
        key: $CI_COMMIT_REF_SLUG
        paths:
            - node_modules/
        policy: pull-push
