version: "3"

services:
    dev_bot:
        build: ../
        restart: always
        environment:
            - BOT_TOKEN
            - API_URL
            - AUTH_TOKEN
        ports:
            - "4848:4848"
        volumes:
            - db-data:/app/storage

volumes:
    db-data:
