version: "3"

services:
    dnb_client:
        build: ../
        depends_on:
            - dnb_db
        environment:
            - BOT_TOKEN
    dnb_db:
        image: mongo
        # ports:
        #     - "27017-27019:27017-27019"
        volumes:
            - "/Volumes/docker/dnb/data/db:/data/db"
        restart: always
