name: Deploy 

on:
  workflow_run:
    workflows: 
      - Image
    types: 
      - completed
    branches: 
      - main

jobs: 
  update-deployment: 
    name: Update Deployment 
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: self-hosted

    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.GH_PAT }}
          repository: pesca-dev/decentnoobbot-deploy
          event-type: decentnoobbot-deploy-trigger
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'
